-- #ex1
SELECT MAX(NUM)
FROM (SELECT COUNT(*) AS NUM
      FROM PENALTIES
      GROUP BY DATA, DELIVERERID)

-- #ex2
SELECT DELIVERERID, SUM(AMOUNT), AVG(AMOUNT)
FROM PENALTIES
GROUP BY DELIVERERID

-- #ex3
SELECT CD1.COMPANYID, CD1.DELIVERERID
FROM COMPANYDEL CD1
WHERE CD1.NUMDELIVERIES = (SELECT MAX(CD2.NUMDELIVERIES)
                           FROM COMPANYDEL CD2
                           WHERE CD1.COMPANYID = CD2.COMPANYID)

-- #ex4
SELECT CD.COMPANYID, CD.DELIVERERID, D.SEX, CD.NUMDELIVERIES
FROM DELIVERERS D, COMPANYDEL CD
WHERE D.DELIVERERID = CD.DELIVERERID AND CD.NUMDELIVERIES = (SELECT MAX(CD2.NUMDELIVERIES)
                                                             FROM DELIVERERS D2, COMPANYDEL CD2
                                                             WHERE D2.DELIVERERID = CD2.DELIVERERID
                                                                   AND D2.SEX = D.SEX AND CD.COMPANYID = CD2.COMPANYID)

-- #ex4b
WITH MAXDELBYCOMPSEX AS (SELECT CD.COMPANYID AS COMPID, D.SEX AS SX, MAX(CD.NUMDELIVERIES) AS MAXIMUM
                         FROM COMPANYDEL CD, DELIVERERS D
                         WHERE CD.DELIVERERID = D.DELIVERERID
                         GROUP BY CD.COMPANYID, D.SEX)
SELECT CD.COMPANYID, CD.DELIVERERID, D.SEX, M.MAXIMUM
FROM COMPANYDEL CD, DELIVERERS D, MAXDELBYCOMPSEX M
WHERE CD.DELIVERERID = D.DELIVERERID AND M.COMPID = CD.COMPANYID AND M.SX = D.SEX AND CD.NUMDELIVERIES = M.MAXIMUM

-- #ex5
SELECT D.DELIVERERID, D.NAME, SUM(P.AMOUNT)
FROM DELIVERERS D, PENALTIES P
WHERE D.DELIVERERID = P.DELIVERERID
GROUP BY D.DELIVERERID, D.NAME
HAVING SUM(P.AMOUNT) > (SELECT AVG(P2.AMOUNT)
                        FROM PENALTIES P2)

-- #ex6
WITH AVINYEAR AS (SELECT EXTRACT(YEAR FROM DATA) AS YEAR, AVG(AMOUNT) AS AVAMOUNT
                  FROM PENALTIES
                  GROUP BY EXTRACT(YEAR FROM DATA))
SELECT P.PAYMENTID, P.DATA, P.AMOUNT, A.AVAMOUNT
FROM PENALTIES P, AVINYEAR A
WHERE EXTRACT(YEAR FROM P.DATA) = A.YEAR AND P.AMOUNT > A.AVAMOUNT

-- #ex7
WITH NUMDELS AS (SELECT DELIVERERID AS ID, SUM(NUMDELIVERIES) AS TOT
                 FROM COMPANYDEL
                 GROUP BY DELIVERERID),
     TOTAVG AS (SELECT AVG(ND2.TOT) AS TOTAVGNUM
                FROM NUMDELS ND2)
SELECT D.TOWN, AVG(ND.TOT), T.TOTAVGNUM
FROM NUMDELS ND, DELIVERERS D, TOTAVG T
WHERE ND.ID = D.DELIVERERID
GROUP BY D.TOWN, T.TOTAVGNUM
HAVING (AVG(ND.TOT)) < T.TOTAVGNUM

-- #ex8
WITH TOTCOL AS (SELECT DELIVERERID, SUM(NUMCOLLECTIONS) AS TOT
                FROM COMPANYDEL
                GROUP BY DELIVERERID),
     AVGCOL AS (SELECT D.YEAR_OF_BIRTH, AVG(TC.TOT) AS AVER
                FROM TOTCOL TC, DELIVERERS D
                WHERE TC.DELIVERERID = D.DELIVERERID
                GROUP BY D.YEAR_OF_BIRTH)
SELECT AC.YEAR_OF_BIRTH
FROM AVGCOL AC
WHERE AC.AVER = (SELECT MAX(AC2.AVER)
                 FROM AVGCOL AC2)

-- #ex9
WITH SUMSEX AS (SELECT D.SEX, COUNT(*) AS NUM
                FROM DELIVERERS D, PENALTIES P
                WHERE D.DELIVERERID = P.DELIVERERID
                GROUP BY D.SEX)
SELECT S.SEX, S.NUM
FROM SUMSEX S
WHERE S.NUM = (SELECT MAX(S2.NUM)
               FROM SUMSEX S2)

-- #ex10
WITH DELSEX AS (SELECT D.SEX, SUM(CD.NUMDELIVERIES) AS TOT
                FROM DELIVERERS D, COMPANYDEL CD
                WHERE D.DELIVERERID = CD.DELIVERERID
                GROUP BY D.SEX)
SELECT DS.SEX, DS.TOT
FROM DELSEX DS
WHERE DS.TOT = (SELECT MAX(DS2.TOT)
                FROM DELSEX DS2)