DROP TABLE HAS;
DROP TABLE HAS2;
DROP TABLE RESERVATION;
DROP TABLE TRAVEL_AGENCY;
DROP TABLE ROOM;
DROP TABLE AMENITY;
DROP TABLE SUITE_SPACES;

/* Tables */
CREATE TABLE TRAVEL_AGENCY (
    Unique_code VARCHAR(255) NOT NULL,
    Street VARCHAR(255) NOT NULL,
    ZIP VARCHAR(255) NOT NULL,
    "Number" INTEGER NOT NULL,
    City VARCHAR(255) NOT NULL,
    "State" VARCHAR(255) NOT NULL,
    Telephone VARCHAR(255) NOT NULL,
    Website VARCHAR(255),
    PRIMARY KEY (Unique_code)
);
CREATE TABLE ROOM (
    Unique_number INTEGER NOT NULL,
    Floor INTEGER NOT NULL,
    Surface_area REAL NOT NULL,
    PRIMARY KEY (Unique_number)
);
CREATE TABLE AMENITY (
    Amenity_ID VARCHAR(255) NOT NULL,
    Name VARCHAR(255) NOT NULL,
    PRIMARY KEY (Amenity_ID)
);
CREATE TABLE SUITE_SPACES (
    Suite_space_ID VARCHAR(255) NOT NULL,
    Name VARCHAR(255) NOT NULL,
    PRIMARY KEY (Suite_space_ID)
);
CREATE TABLE RESERVATION (
    ROOM_Unique_number INTEGER NOT NULL,
    Start_date VARCHAR(255) NOT NULL,
    End_date VARCHAR(255) NOT NULL,
    Daily_price REAL NOT NULL,
    TRAVEL_AGENCY_Alpha_code VARCHAR(255) NOT NULL,
    PRIMARY KEY (ROOM_Unique_number, Start_date),
    FOREIGN KEY (ROOM_Unique_number) REFERENCES ROOM (Unique_number),
    FOREIGN KEY (TRAVEL_AGENCY_Alpha_code) REFERENCES TRAVEL_AGENCY (Unique_code)
);
CREATE TABLE HAS2 (
    ROOM_Unique_number INTEGER NOT NULL,
    SUITE_SPACES_Suite_space_ID VARCHAR(255) NOT NULL,
    PRIMARY KEY (ROOM_Unique_number, SUITE_SPACES_Suite_space_ID),
    FOREIGN KEY (ROOM_Unique_number) REFERENCES ROOM(Unique_number),
    FOREIGN KEY (SUITE_SPACES_Suite_space_ID) REFERENCES SUITE_SPACES(Suite_space_ID)
);
CREATE TABLE HAS (
    ROOM_Unique_number INTEGER NOT NULL,
    AMENITY_Amenity_ID VARCHAR(255) NOT NULL,
    PRIMARY KEY (ROOM_Unique_number, AMENITY_Amenity_ID),
    FOREIGN KEY (ROOM_Unique_number) REFERENCES ROOM(Unique_number),
    FOREIGN KEY (AMENITY_Amenity_ID) REFERENCES AMENITY(Amenity_ID)
);